// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXM7np2-M8QQ7ol4MaZBIX6_ftFYbOTjU',
    appId: '1:281917164496:web:5083c5dc27cbfaba8cc7d5',
    messagingSenderId: '281917164496',
    projectId: 'minhascompras-3abbe',
    authDomain: 'minhascompras-3abbe.firebaseapp.com',
    storageBucket: 'minhascompras-3abbe.firebasestorage.app',
    measurementId: 'G-GRM5ZHREN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUX3jPBSdSwRkSS8NL3jw3AlGlX6Bnpgc',
    appId: '1:281917164496:android:2900aefd61199e838cc7d5',
    messagingSenderId: '281917164496',
    projectId: 'minhascompras-3abbe',
    storageBucket: 'minhascompras-3abbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-g3bDn7faQs9oLAmjVIphC5JDpGH1hA',
    appId: '1:281917164496:ios:b257ff81f4376aa08cc7d5',
    messagingSenderId: '281917164496',
    projectId: 'minhascompras-3abbe',
    storageBucket: 'minhascompras-3abbe.firebasestorage.app',
    iosClientId: '281917164496-6mhg4v7mbi8j81g4v5udufjpi4h6839s.apps.googleusercontent.com',
    iosBundleId: 'com.example.listaComprasMaterial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS-g3bDn7faQs9oLAmjVIphC5JDpGH1hA',
    appId: '1:281917164496:ios:b257ff81f4376aa08cc7d5',
    messagingSenderId: '281917164496',
    projectId: 'minhascompras-3abbe',
    storageBucket: 'minhascompras-3abbe.firebasestorage.app',
    iosClientId: '281917164496-6mhg4v7mbi8j81g4v5udufjpi4h6839s.apps.googleusercontent.com',
    iosBundleId: 'com.example.listaComprasMaterial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXM7np2-M8QQ7ol4MaZBIX6_ftFYbOTjU',
    appId: '1:281917164496:web:e34a7fd57cf3ace58cc7d5',
    messagingSenderId: '281917164496',
    projectId: 'minhascompras-3abbe',
    authDomain: 'minhascompras-3abbe.firebaseapp.com',
    storageBucket: 'minhascompras-3abbe.firebasestorage.app',
    measurementId: 'G-62T030K11E',
  );
}
